# Generated by Django 3.2.6 on 2021-08-03 08:50

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='feature_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='core.category'),
        ),
    ]
