# Generated by Django 3.2.6 on 2021-08-03 12:10

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_article_featured_mob_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_mob_img',
            field=models.ImageField(blank=True, null=True, upload_to='feature_mob_images/'),
        ),
    ]
