# Generated by Django 3.2.6 on 2021-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.Tag'),
        ),
    ]
